name: K6 testes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run K6 Load Test
        run: k6 run path/to/your/script.js
