name: K6 testes
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run K6 Load Test
        run: k6 run ./scenarios/Get-Customer.js
