name: K6 testes
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          curl -OL "https://github.com/k6io/k6/releases/download/v0.34.1/k6-v0.34.1-linux64.tar.gz"
          tar xzvf k6-v0.34.1-linux64.tar.gz
          sudo mv k6-v0.34.1-linux64/k6 /usr/local/bin/
          rm -rf k6-v0.34.1-linux64 k6-v0.44.1-linux64.tar.gz

      - name: Run K6 Load Test
        run: k6 run ./scenarios/Get-Customer.js
