name: K6 testes
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo sh -c "echo 'deb https://dl.bintray.com/loadimpact/deb stable main' | tee /etc/apt/sources.list.d/k6.list"
          sudo apt-get install -y k6

      - name: Run K6 Load Test
        run: k6 run ./scenarios/Get-Customer.js
